### ISSUE TITLE
Creating a separate controllers section

### ISSUE THREAD

**Issue by HrutikaBadgeri** [akshatkumar27/Task-manager#1]
Hey, I looked through the project and noticed that all of your controller functions are written within the routes, it would be great to have them separately i.e. all the controller functions (CRUD operations) for the tasks in a separate folder. And the routes will only contain the API calls for the specific operations the user wants to perform.  This is basically just to improve the structure of your overall project code. I would love to work on it. What do you think? Let me know  :)

**Comment by akshatkumar27** [comment]
Sure i would be happy to assign this issue to you

**Comment by HrutikaBadgeri** [comment]
That's great! Can you assign me this issue under Hacktober Fest? I will start working on it and raise a PR as soon as I can :)

**Comment by akshatkumar27** [comment]
Your username is not appearing for assign so just fork the repo and send PR I 'll merge it .

**Comment by HrutikaBadgeri** [comment]
Hey, I have raised a PR! Can you check it out? Also, after reviewing, can you please add my PR under the Hacktober Fest tags?

**Comment by HrutikaBadgeri** [comment]
Hey, are you there?
